name: CI

on:
  push:
    tags:
      - '*'
jobs:
  main:
    uses: visibilityspots/dockerfile-cloudflared/.github/workflows/main.yml@main
    with:
      platforms: "linux/amd64,linux/arm64"
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
